export const GET_ALL_MOVIE_GENRES='GET_ALL_MOVIE_GENRES';
export const GET_ALL_MOVIES_BY_GENRE='GET_ALL_MOVIES_BY_GENRE';
export const GET_TRENDING_MOVIES='GET_TRENDING_MOVIES';
export const MOVIE_SEARCH='MOVIE_SEARCH';
export const GET_SEARCH_MOVIES='GET_SEARCH_MOVIES';
export const GET_MOVIE_DETAILS='GET_MOVIE_DETAILS';
