// MOVIE TYPES
export const GET_ALL_MOVIE_GENRES='GET_ALL_MOVIE_GENRES';
export const GET_ALL_MOVIES_BY_GENRE='GET_ALL_MOVIES_BY_GENRE';
export const GET_TRENDING_MOVIES='GET_TRENDING_MOVIES';
export const MOVIE_SEARCH='MOVIE_SEARCH';
export const GET_SEARCH_MOVIES='GET_SEARCH_MOVIES';
export const GET_MOVIE_DETAILS='GET_MOVIE_DETAILS';
export const CLEAR_MOVIE='CLEAR_MOVIE';

// TV TYPES
export const GET_ALL_SHOW_GENRES='GET_ALL_SHOW_GENRES';
export const GET_ALL_SHOWS_BY_GENRE='GET_ALL_SHOWS_BY_GENRE';
export const GET_ANIME_SHOWS='GET_ANIME_SHOWS';
export const GET_TRENDING_SHOWS='GET_TRENDING_SHOWS';
export const SHOW_SEARCH='SHOW_SEARCH';
export const GET_SEARCH_SHOWS='GET_SEARCH_SHOWS';
export const GET_SHOW_DETAILS='GET_SHOW_DETAILS';
export const CLEAR_SHOW='CLEAR_SHOW';